# Numpy Arrays

In [1]:
mylist = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.32732965, 0.86127863, 0.25620442, 0.75460972, 0.80836524])

In [19]:
np.random.rand(5,5)

array([[0.52821539, 0.03905882, 0.915074  , 0.97815161, 0.60789377],
       [0.70817055, 0.97141144, 0.7979181 , 0.53071343, 0.64693883],
       [0.01708313, 0.42930378, 0.50446181, 0.48524395, 0.34291065],
       [0.38540737, 0.86089793, 0.24210658, 0.37772849, 0.33585065],
       [0.58541098, 0.36366754, 0.48459297, 0.14439179, 0.75022478]])

In [21]:
np.random.randn(4,4)

array([[ 0.47235062, -0.35113209, -1.57497222,  1.09512516],
       [ 0.3930288 , -1.07106099,  0.53245554,  0.87851369],
       [-1.17794194,  0.78794574,  0.24545532,  0.0500357 ],
       [ 0.46256548,  0.53252092, -0.61630456, -0.84238679]])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([ 5,  1, 24, 22, 24, 30, 39, 10, 40,  8])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.shape

(25,)

In [33]:
ranarr.max()

40

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmax()

8

In [36]:
ranarr.argmin()

1

In [37]:
arr.dtype

dtype('int32')

# Indexing and Selection

In [38]:
import numpy as np

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5] = 100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr = arr[2:5]

In [51]:
slice_of_arr

array([2, 3, 4])

In [52]:
arr_copy = arr.copy()

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr_copy[:] = 100

In [55]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Indexing 2D array - Also called Matrix

In [57]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
#DOUBLE BRACKET FORMAT
arr_2d[0][0]

5

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [62]:
arr_2d[1][1]

25

In [64]:
arr_2d[2][1]

40

In [65]:
#SINGLE BRACK NOTATION
arr_2d[2,1]

40

In [68]:
#GET SUBSECTION FROM THE ARRAY
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_2d[1:,]

array([[20, 25, 30],
       [35, 40, 45]])

In [72]:
#Conditional Selection
arr = np.arange(1,11)

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr > 5

In [76]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr<3]

array([1, 2])

***Numpy Operation***

In [80]:
arr = np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [87]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [88]:
1/0

ZeroDivisionError: division by zero

In [89]:
arr / arr

<ipython-input-89-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [90]:
1/arr

<ipython-input-90-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [91]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [93]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [94]:
np.max(arr)

10

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [96]:
np.log(arr)

<ipython-input-96-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])