In [1]:
import pandas as pd
import nltk
nltk.download("all")

from nltk.sentiment.vader import SentimentIntensityAnalyzer
import string
import re


df_train = pd.read_csv("sentiment_train.csv")

print(df_train.info())
print(df_train.head())

df_test = pd.read_csv("sentiment_test.csv")

print(df_train.info())
print(df_train.head())

# TODO

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\ishik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\ishik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\ishik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\ishik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\ishik\AppData\Roaming\nltk_data...
[nltk_data]    | 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Sentence  2400 non-null   object
 1   Polarity  2400 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 37.6+ KB
None
                                            Sentence  Polarity
0                           Wow... Loved this place.         1
1                                 Crust is not good.         0
2          Not tasty and the texture was just nasty.         0
3  Stopped by during the late May bank holiday of...         1
4  The selection on the menu was great and so wer...         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Sentence  2400 non-null   object
 1   Polarity  2400 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 37.6+ KB

In [2]:
from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [3]:
df_train.shape

(2400, 2)

In [75]:
df_test.shape

(600, 6)

In [ ]:
#Methods to try
#1. Check the imbalance of the data
#2. Check the missing values
#3. Clean the text column
#4. Apply Sentiment Analysis
#5. 

#### There is no imbalancing in the data as the label are equally distributed

In [5]:
#Check for missing data
df_train[df_train["Sentence"] =="#NAME?"]

Sentence  Polarity
26    #NAME?         0
71    #NAME?         1
219   #NAME?         1
904   #NAME?         0

In [6]:
#Deleting rows with error entries
df_train.drop([26,71,219,904],inplace = True)

In [7]:
df_train.shape

(2396, 2)

In [8]:
df_train = df_train.reset_index(drop = True)

In [9]:
#Checking the rows after removing them
df_train[df_train["Sentence"] =="#NAME?"]

Empty DataFrame
Columns: [Sentence, Polarity]
Index: []

In [10]:
sid = SentimentIntensityAnalyzer()

In [11]:
#applying sentiment analysis to each row of the column
df_train["scores"] = df_train["Sentence"].apply(lambda pappu:sid.polarity_scores(pappu))

In [12]:
df_train.shape

(2396, 3)

In [13]:
df_train["compound_score"] = df_train["scores"].apply(lambda di:di["compound"])

In [14]:
df_train.head(5)

Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                              scores  compound_score  
0  {'neg': 0.0, 'neu': 0.435, 'pos': 0.565, 'comp...          0.5994  
1  {'neg': 0.445, 'neu': 0.555, 'pos': 0.0, 'comp...         -0.3412  
2  {'neg': 0.34, 'neu': 0.66, 'pos': 0.0, 'compou...         -0.5574  
3  {'neg': 0.093, 'neu': 0.585, 'pos': 0.322, 'co...          0.6908  
4  {'neg': 0.0, 'neu': 0.728, 'pos': 0.272, 'comp...          0.6249

In [15]:
#Adding negative score column to the dataframe
df_train["negative_score"] = df_train["scores"].apply(lambda di:di["neg"])

In [16]:
df_train.head(5)

Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                              scores  compound_score  \
0  {'neg': 0.0, 'neu': 0.435, 'pos': 0.565, 'comp...          0.5994   
1  {'neg': 0.445, 'neu': 0.555, 'pos': 0.0, 'comp...         -0.3412   
2  {'neg': 0.34, 'neu': 0.66, 'pos': 0.0, 'compou...         -0.5574   
3  {'neg': 0.093, 'neu': 0.585, 'pos': 0.322, 'co...          0.6908   
4  {'neg': 0.0, 'neu': 0.728, 'pos': 0.272, 'comp...          0.6249   

   negative_score  
0           0.000  
1           0.445  
2           0.340  
3           0.093  
4           0.000

In [17]:
#Adding positive score column to the dataframe
df_train["positive_score"] = df_train["scores"].apply(lambda di:di["pos"])

In [18]:
#Creating X and Y train dataset
    X = df_train.drop('Polarity',axis = 1,inplace = False)

In [19]:
X.shape

(2396, 5)

In [20]:
y = df_train['Polarity']

In [21]:
y.shape

(2396,)

In [22]:
#Processing the entire data by defining the function called 'text_clean'

def text_clean(text):
    r = text.translate(str.maketrans("","",string.punctuation)) #Remove All Punctuations
    r = re.sub(r'\d+', '',r) #remove numbers
    r = r.lower() #Lowercase the string
    r = r.split() #Split the strings on white spaces
    r = [word for word in r if word not in stopwords.words('english')] #Remove Stopwords
    r = [lemmatizer.lemmatize(word) for word in r] #Lemmatization
    r = ' '.join(r) #Joining back the words to make the entire string
    return r

In [23]:
X['processedText'] = X['Sentence'].apply(lambda x: text_clean(x))

In [24]:
X.head(5)

Sentence  \
0                           Wow... Loved this place.   
1                                 Crust is not good.   
2          Not tasty and the texture was just nasty.   
3  Stopped by during the late May bank holiday of...   
4  The selection on the menu was great and so wer...   

                                              scores  compound_score  \
0  {'neg': 0.0, 'neu': 0.435, 'pos': 0.565, 'comp...          0.5994   
1  {'neg': 0.445, 'neu': 0.555, 'pos': 0.0, 'comp...         -0.3412   
2  {'neg': 0.34, 'neu': 0.66, 'pos': 0.0, 'compou...         -0.5574   
3  {'neg': 0.093, 'neu': 0.585, 'pos': 0.322, 'co...          0.6908   
4  {'neg': 0.0, 'neu': 0.728, 'pos': 0.272, 'comp...          0.6249   

   negative_score  positive_score  \
0           0.000           0.565   
1           0.445           0.000   
2           0.340           0.000   
3           0.093           0.322   
4           0.000           0.272   

                                       processedText  
0                                    wow loved place  
1                                         crust good  
2                                tasty texture nasty  
3  stopped late may bank holiday rick steve recom...  
4                         selection menu great price

In [ ]:
X.shape

In [ ]:
#Tokenize the words

#X["tokenizedWords"] = X["processedText"].apply(lambda words: nltk.word_tokenize(words))

In [ ]:
#X.head(5)

In [ ]:
#Drop the tokenizedWords column
#X = X.drop("tokenizedWords", axis = 1)

In [ ]:
#X.head(5)

In [25]:
#X_text variable containing the list of sentence column
X_text = X["processedText"]

In [26]:
X_text.shape

(2396,)

In [27]:
#CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [28]:
#Applying countvectorizer to X_text column
count_vect = cv.fit_transform(X_text)

In [29]:
count_vect

<2396x3628 sparse matrix of type '<class 'numpy.int64'>'
	with 13321 stored elements in Compressed Sparse Row format>

In [30]:
# convert X to array
X_array = count_vect.toarray()

In [31]:
# check type of X_array
type(X_array)

numpy.ndarray

In [32]:
# shape of X_array
X_array.shape

(2396, 3628)

In [33]:
print(X_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [34]:
# convert X_array into pandas dataframe
import pandas as pd
df = pd.DataFrame(X_array)
df

0     1     2     3     4     5     6     7     8     9     ...  3618  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2391     0     0     0     0     0     0     0     0     0     0  ...     0   
2392     0     0     0     0     0     0     0     0     0     0  ...     0   
2393     0     0     0     0     0     0     0     0     0     0  ...     0   
2394     0     0     0     0     0     0     0     0     0     0  ...     0   
2395     0     0     0     0     0     0     0     0     0     0  ...     0   

      3619  3620  3621  3622  3623  3624  3625  3626  3627  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2391     0     0     0     0     0     0     0     0     0  
2392     0     0     0     0     0     0     0     0     0  
2393     0     0     0     0     0     0     0     0     0  
2394     0     0     0     0     0     0     0     0     0  
2395     0     0     0     0     0     0     0     0     0  

[2396 rows x 3628 columns]

In [35]:
# assign column names to df
df.columns = cv.get_feature_names()
df.shape

(2396, 3628)

In [36]:
# You can now concat these features in the original data
new_data = pd.concat([X,df], axis=1)
new_data

Sentence  \
0                              Wow... Loved this place.   
1                                    Crust is not good.   
2             Not tasty and the texture was just nasty.   
3     Stopped by during the late May bank holiday of...   
4     The selection on the menu was great and so wer...   
...                                                 ...   
2391  Almost all of the songs in Cover Girl are old-...   
2392  The most annoying thing about 'Cover Girl' is ...   
2393  Unfortunately, 'Cover Girl' is an example of h...   
2394  Non-linear narration thus many flashbacks and ...   
2395  The good cinematography also makes her and Mon...   

                                                 scores  compound_score  \
0     {'neg': 0.0, 'neu': 0.435, 'pos': 0.565, 'comp...          0.5994   
1     {'neg': 0.445, 'neu': 0.555, 'pos': 0.0, 'comp...         -0.3412   
2     {'neg': 0.34, 'neu': 0.66, 'pos': 0.0, 'compou...         -0.5574   
3     {'neg': 0.093, 'neu': 0.585, 'pos': 0.322, 'co...          0.6908   
4     {'neg': 0.0, 'neu': 0.728, 'pos': 0.272, 'comp...          0.6249   
...                                                 ...             ...   
2391  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...          0.0000   
2392  {'neg': 0.143, 'neu': 0.857, 'pos': 0.0, 'comp...         -0.4576   
2393  {'neg': 0.188, 'neu': 0.644, 'pos': 0.168, 'co...          0.1531   
2394  {'neg': 0.0, 'neu': 0.821, 'pos': 0.179, 'comp...          0.3384   
2395  {'neg': 0.0, 'neu': 0.585, 'pos': 0.415, 'comp...          0.7960   

      negative_score  positive_score  \
0              0.000           0.565   
1              0.445           0.000   
2              0.340           0.000   
3              0.093           0.322   
4              0.000           0.272   
...              ...             ...   
2391           0.000           0.000   
2392           0.143           0.000   
2393           0.188           0.168   
2394           0.000           0.179   
2395           0.000           0.415   

                                          processedText  abhor  ability  able  \
0                                       wow loved place      0        0     0   
1                                            crust good      0        0     0   
2                                   tasty texture nasty      0        0     0   
3     stopped late may bank holiday rick steve recom...      0        0     0   
4                            selection menu great price      0        0     0   
...                                                 ...    ...      ...   ...   
2391        almost song cover girl oldfashioned tuneful      0        0     0   
2392  annoying thing cover girl way rita hayworth pu...      0        0     0   
2393  unfortunately cover girl example hollywood use...      0        0     0   
2394  nonlinear narration thus many flashback every ...      0        0     0   
2395  good cinematography also make monica bellucci ...      0        0     0   

      abound  ...  young  youre  youthful  yucky  yukon  yum  yummy  za  zero  \
0          0  ...      0      0         0      0      0    0      0   0     0   
1          0  ...      0      0         0      0      0    0      0   0     0   
2          0  ...      0      0         0      0      0    0      0   0     0   
3          0  ...      0      0         0      0      0    0      0   0     0   
4          0  ...      0      0         0      0      0    0      0   0     0   
...      ...  ...    ...    ...       ...    ...    ...  ...    ...  ..   ...   
2391       0  ...      0      0         0      0      0    0      0   0     0   
2392       0  ...      0      0         0      0      0    0      0   0     0   
2393       0  ...      0      0         0      0      0    0      0   0     0   
2394       0  ...      0      0         0      0      0    0      0   0     0   
2395       0  ...      0      0         0      0      0    0      0   0     0   

      zomb

In [38]:
new_data = new_data.drop(["Sentence","scores","processedText"],axis = 1)

In [39]:
new_data.head(5)

compound_score  negative_score  positive_score  abhor  ability  able  \
0          0.5994           0.000           0.565      0        0     0   
1         -0.3412           0.445           0.000      0        0     0   
2         -0.5574           0.340           0.000      0        0     0   
3          0.6908           0.093           0.322      0        0     0   
4          0.6249           0.000           0.272      0        0     0   

   abound  abovepretty  absolute  absolutel  ...  young  youre  youthful  \
0       0            0         0          0  ...      0      0         0   
1       0            0         0          0  ...      0      0         0   
2       0            0         0          0  ...      0      0         0   
3       0            0         0          0  ...      0      0         0   
4       0            0         0          0  ...      0      0         0   

   yucky  yukon  yum  yummy  za  zero  zombiez  
0      0      0    0      0   0     0        0  
1      0      0    0      0   0     0        0  
2      0      0    0      0   0     0        0  
3      0      0    0      0   0     0        0  
4      0      0    0      0   0     0        0  

[5 rows x 3631 columns]

### Part 1.b. Modeling

Use your favorite ML algorithm to train a classification model.  Don’t forget everything that we’ve learned in our ML course: hyperparameter tuning, cross validation, handling imbalanced data, etc. Make reasonable decisions and try to create the best-performing classifier that you can.

In [40]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [54]:
param = {'C':[0,0.01,0.1,1,10,100],
         'penalty':["l1","l2"],
         'solver': ["lbfgs","liblinear"]
                   }

In [55]:
#Importing the required package for GridSearchCV
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(lr,param,cv = 3,scoring = "roc_auc")

In [56]:
grid.fit(new_data,y)

C:\Users\ishik\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\ishik\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ishik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ishik\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\ishik\anaconda3\lib\site-packages\sklearn\model_selection\_v

GridSearchCV(cv=3, estimator=LogisticRegression(),
             param_grid={'C': [0, 0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2'],
                         'solver': ['lbfgs', 'liblinear']},
             scoring='roc_auc')

In [57]:
grid.best_score_

0.9185097854572968

In [58]:
grid.best_params_

{'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}

In [59]:
#Making changes to the testing data
#Check for missing data
df_test[df_test["Sentence"] =="#NAME?"]

Empty DataFrame
Columns: [Sentence, Polarity]
Index: []

In [61]:
df_test.isnull().sum()

Sentence    0
Polarity    0
dtype: int64

In [62]:
#Creating scores column by applying sentiment analysis
df_test["scores"] = df_test["Sentence"].apply(lambda pappu:sid.polarity_scores(pappu))

In [63]:
#Creating a compound score feature on the test dataset
df_test["compound_score"] = df_test["scores"].apply(lambda di:di["compound"])

In [64]:
#Creating negative score column
df_test["negative_score"] = df_test["scores"].apply(lambda di:di["neg"])

In [65]:
#Creating positive score column
df_test["positive_score"] = df_test["scores"].apply(lambda di:di["pos"])

In [66]:
df_test.head(5)

Sentence  Polarity  \
0  A good commentary of today's love and undoubte...         1   
1  For people who are first timers in film making...         1   
2  It was very popular when I was in the cinema, ...         1   
3  It's a feel-good film and that's how I felt wh...         1   
4  It has northern humour and positive about the ...         1   

                                              scores  compound_score  \
0  {'neg': 0.0, 'neu': 0.438, 'pos': 0.562, 'comp...          0.8402   
1  {'neg': 0.0, 'neu': 0.766, 'pos': 0.234, 'comp...          0.6467   
2  {'neg': 0.0, 'neu': 0.554, 'pos': 0.446, 'comp...          0.9020   
3  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...          0.0000   
4  {'neg': 0.0, 'neu': 0.573, 'pos': 0.427, 'comp...          0.7717   

   negative_score  positive_score  
0             0.0           0.562  
1             0.0           0.234  
2             0.0           0.446  
3             0.0           0.000  
4             0.0           0.427

In [67]:
#Creating X_test dataset
X_test = df_test.drop('Polarity',axis = 1,inplace = False)

In [68]:
#Creating y_test dataset
y_test = df_test['Polarity']

In [69]:
#Applying the text cleaning function on the test dataset
X_test['processedText'] = X_test['Sentence'].apply(lambda x: text_clean(x))

In [70]:
#Creating text column with the processed data for creating count vectorizer
test_text = X_test["processedText"]

In [71]:
#Fitting Count Vectorizer on the test dataset
test_vect = cv.transform(test_text)

In [72]:
#Converting test_vect to array
test_array = test_vect.toarray()

In [73]:
# convert test_array into pandas dataframe
testdf = pd.DataFrame(test_array)
testdf

0     1     2     3     4     5     6     7     8     9     ...  3618  \
0       0     0     0     0     0     0     0     0     0     0  ...     0   
1       0     0     0     0     0     0     0     0     0     0  ...     0   
2       0     0     0     0     0     0     0     0     0     0  ...     0   
3       0     0     0     0     0     0     0     0     0     0  ...     0   
4       0     0     0     0     0     0     0     0     0     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
595     0     0     0     0     0     0     0     0     0     0  ...     0   
596     0     0     0     0     0     0     0     0     0     0  ...     0   
597     0     0     0     0     0     0     0     0     0     0  ...     0   
598     0     0     0     0     0     0     0     0     0     0  ...     0   
599     0     0     0     0     0     0     0     0     0     0  ...     0   

     3619  3620  3621  3622  3623  3624  3625  3626  3627  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
595     0     0     0     0     0     0     0     0     0  
596     0     0     0     0     0     0     0     0     0  
597     0     0     0     0     0     0     0     0     0  
598     0     0     0     0     0     0     0     0     0  
599     0     0     0     0     0     0     0     0     0  

[600 rows x 3628 columns]

In [74]:
# assign column names to testdf
testdf.columns = cv.get_feature_names()
testdf.shape

(600, 3628)

In [76]:
## You can now concat these features in the original data
test_new_data = pd.concat([X_test,testdf], axis=1)
test_new_data

Sentence  \
0    A good commentary of today's love and undoubte...   
1    For people who are first timers in film making...   
2    It was very popular when I was in the cinema, ...   
3    It's a feel-good film and that's how I felt wh...   
4    It has northern humour and positive about the ...   
..                                                 ...   
595  I just got bored watching Jessice Lange take h...   
596  Unfortunately, any virtue in this film's produ...   
597                   In a word, it is embarrassing.     
598                               Exceptionally bad!     
599  All in all its an insult to one's intelligence...   

                                                scores  compound_score  \
0    {'neg': 0.0, 'neu': 0.438, 'pos': 0.562, 'comp...          0.8402   
1    {'neg': 0.0, 'neu': 0.766, 'pos': 0.234, 'comp...          0.6467   
2    {'neg': 0.0, 'neu': 0.554, 'pos': 0.446, 'comp...          0.9020   
3    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...          0.0000   
4    {'neg': 0.0, 'neu': 0.573, 'pos': 0.427, 'comp...          0.7717   
..                                                 ...             ...   
595  {'neg': 0.21, 'neu': 0.79, 'pos': 0.0, 'compou...         -0.3382   
596  {'neg': 0.404, 'neu': 0.455, 'pos': 0.141, 'co...         -0.6369   
597  {'neg': 0.394, 'neu': 0.606, 'pos': 0.0, 'comp...         -0.3818   
598  {'neg': 0.803, 'neu': 0.197, 'pos': 0.0, 'comp...         -0.6230   
599  {'neg': 0.284, 'neu': 0.465, 'pos': 0.251, 'co...         -0.1779   

     negative_score  positive_score  \
0             0.000           0.562   
1             0.000           0.234   
2             0.000           0.446   
3             0.000           0.000   
4             0.000           0.427   
..              ...             ...   
595           0.210           0.000   
596           0.404           0.141   
597           0.394           0.000   
598           0.803           0.000   
599           0.284           0.251   

                                         processedText  abhor  ability  able  \
0    good commentary today love undoubtedly film wo...      0        0     0   
1    people first timer film making think excellent...      0        0     0   
2    popular cinema good house good reaction plenty...      0        0     0   
3                 feelgood film thats felt came cinema      0        0     0   
4        northern humour positive community represents      0        0     0   
..                                                 ...    ...      ...   ...   
595      got bored watching jessice lange take clothes      0        0     0   
596  unfortunately virtue film production work lost...      0        0     0   
597                                  word embarrassing      0        0     0   
598                                  exceptionally bad      0        0     0   
599           insult one intelligence huge waste money      0        0     0   

     abound  ...  young  youre  youthful  yucky  yukon  yum  yummy  za  zero  \
0         0  ...      0      0         0      0      0    0      0   0     0   
1         0  ...      0      0         0      0      0    0      0   0     0   
2         0  ...      0      0         0      0      0    0      0   0     0   
3         0  ...      0      0         0      0      0    0      0   0     0   
4         0  ...      0      0         0      0      0    0      0   0     0   
..      ...  ...    ...    ...       ...    ...    ...  ...    ...  ..   ...   
595       0  ...      0      0         0      0      0    0      0   0     0   
596       0  ...      0      0         0      0      0    0      0   0     0   
597       0  ...      0      0         0      0      0    0      0   0     0   
598       0  ...      0      0         0      0      0    0      0   0     0   
599       0  ...      0      0         0      0      0    0      0   0     0   

     zombiez  
0          0  
1          0  
2          0  
3        

In [77]:
#Removing text columns from the dataset before applying the logistic regression model
test_new_data = test_new_data.drop(["Sentence","scores","processedText"],axis = 1)

In [78]:
#Making prediction on the test dataset using the best model
predictions = grid.predict(test_new_data)

In [80]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.76      0.91      0.82       287
           1       0.89      0.73      0.80       313

    accuracy                           0.81       600
   macro avg       0.83      0.82      0.81       600
weighted avg       0.83      0.81      0.81       600

